version: '3.8'
services:
  garuda-user:
    container_name: garuda-user
    image: garuda-user:latest
    networks:
      - garuda-network
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NOTIFICATION_ENDPOINT=http://garuda-notification:8082/api/v1/notification
      - TRACING_ENDPOINT=http://otel-collector:4318/v1/traces
      - METRIC_ENDPOINT=http://otel-collector:4318/v1/metrics
    depends_on:
      - otel-collector
      - jaeger
      - prometheus
      - garuda-notification
  garuda-notification:
    container_name: garuda-notification
    image: garuda-notification:latest
    networks:
      - garuda-network
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TRACING_ENDPOINT=http://otel-collector:4318/v1/traces
      - METRIC_ENDPOINT=http://otel-collector:4318/v1/metrics
    depends_on:
      - otel-collector
      - jaeger
      - prometheus
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.82.0
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./infrastructure/opentelemetry/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
#    ports: # Uncomment for local development
#      - "1888:1888" # pprof extension
#      - "8888:8888" # Prometheus metrics exposed by the collector
#      - "8889:8889" # Prometheus exporter metrics
#      - "13133:13133" # health_check extension
#      - "4317:4317" # OTLP gRPC receiver
#      - "4318:4318" # OTLP http receiver
#      - "55679:55679" # zpages extension
    depends_on:
      - prometheus
      - jaeger
    networks:
      - garuda-network
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # the jaeger UI
    environment:
      - COLLECTOR_OTLP_ENABLED=true #enable otel protocol format
    networks:
      - garuda-network
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"
    networks:
      - garuda-network
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./infrastructure/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "13000:3000"
    networks:
      - garuda-network
networks:
  garuda-network: