server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: garuda-notification

logging:
  level:
    com.garuda.notification: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


management:
  web:
    exposure:
      include: health
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 3s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0
