global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
        labels:
          application: 'otel-collector'